global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.163.com:465'    
  smtp_from: '替换'       # 发件人
  smtp_auth_username: '替换'
  smtp_auth_password: '替换'  # 邮箱授权码（非登录密码）
  smtp_require_tls: false              # 关闭 TLS 加密

route:
  group_by: ['alertname']             # 按告警名称分组
  group_wait: 30s                     # 组内等待时间
  group_interval: 5m                 # 组间间隔
  repeat_interval: 1h                # 重复告警间隔
  receiver: 'email'                   # 默认接收器

receivers:
- name: 'email'
  email_configs:
  - to: '替换'         # 收件人
    send_resolved: true              # 发送恢复通知
