version: '3.8'

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        restart: always
        environment:
            - TZ=Asia/Shanghai
        networks:
            - prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus/data:/prometheus:rw
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/rules:/etc/prometheus/rules

    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        restart: always
        environment:
            - Tz=Asia/Shanghai
        networks:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - ./grafana/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/data:/var/lib/grafana:rw

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        restart: always
        ports:
        - "9100:9100"
        volumes:
        - "/proc:/host/proc:ro"
        - "/sys:/host/sys:ro"
        - "/:/rootfs:ro"
        command:
        - "--path.procfs=/host/proc"
        - "--path.sysfs=/host/sys"

    consul:
        image: consul:1.15.4
        container_name: consul
        hostname: consul
        restart: always
        ports:
        - "8500:8500"
        volumes:
        - "./consul/data:/consul/data"
        - "./consul/conf.d:/consul/config/conf.d"

networks:
    prometheus:
        driver: bridge
